CREATE TABLE STUDENTS
(
NAME nvarchar(20) NOT NULL,
SURNAME nvarchar (40) DEFAULT 'XXX',
AGE tinyint check(AGE>18),
AVGPOINT decimal
)
INSERT INTO STUDENTS (NAME,SURNAME,AGE,AVGPOINT)
VALUES
(N'Rəfigə',N'Mirzəzadə', 20,100 ),
(N'NURAY',N'Qasimli', 22,48 ),
(N'MƏLək',N'Əliyeva', 29,59 ),
(N'Ali',N'Cavadov', 19,77 ),
(N'Alixan ',N'Quliyev', 32,99 )

SELECT * FROM STUDENTS
WHERE (AVGPOINT>51)

SELECT * FROM STUDENTS
WHERE AVGPOINT BETWEEN 51 AND 90

SELECT * FROM STUDENTS
WHERE NAME LIKE 'A%' AND  NAME LIKE '%i' 

SELECT * FROM STUDENTS
